### ISSUE TITLE
🤔 typescript 설치 오류 문제

### ISSUE THREAD

**Issue by yamoo9** [yamoo9/react-ssafy#9]
## 설치 오류

typescript 패키지 설치 과정에서 아래 에러가 나면 어떻게 해야 하나요??

```sh
SKIPPING OPTIONAL DEPENDENCY: 
Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} 
(current: {"os":"win32","arch":"x64"}) 
```

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 Windows
- Node.js 버전 v14.17.6

**Comment by swany0509** [comment]
node version
v14.17.6
입니다.

**Comment by yamoo9** [comment]
## 문제 원인

[fsevents](https://www.npmjs.com/package/fsevents) 모듈은 macOS 용이라 
Windows OS에서 지원하지 않아서 경고 메시지가 출력된 것입니다. 🤔

## 문제 해결 방법

이 경고 메시지가 출력되지 않고 설치되도록 하려면 `package.json` 파일에 
선택적 종속성([optionalDependencies](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#optionaldependencies)) 항목을 추가한 다음 아래와 같이 작성합니다.

```json
{
  "optionalDependencies": {
    "fsevents": "*"
  }
}
```

이 설정은 종속성을 사용할 수 있지만 찾을 수 없거나 설치에 실패한 경우 
`optionalDependencies` 항목 객체에 추가할 수 있습니다. 

종속성([dependencies](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#dependencies)) 항목과 마찬가지로 패키지 이름, 버전 정보를 설정합니다.
차이점은 설치 과정에서 실패하더라도 오류를 출력하지 않습니다.

패키지를 설치할 때 --omit 옵션 플래그를 아래와 같이 설정하면 오류 메시지가 출력되지 않을 것입니다. 😉

```sh
npm install --omit=optioinal
```
